title: Frank Romero Studio
description: >-
  Chicano artist Frank Ramero's official website.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.frankromero.art" # the base hostname & protocol for your site
enforce_ssl: "www.frankromero.art"
cloudinary: "https://res.cloudinary.com/frank-romero/image/upload/"
social: 
  name: Frank Romero
  links:
    - https://www.instagram.com/frankromeroartist/
    - https://www.facebook.com/FrankEdwardRomero/

exclude: [
  'Gemfile',
  'Gemfile.lock',
  'README.md'
]

# Build settings
markdown: kramdown

liquid:
  error_mode: strict

plugins:
  - jekyll-feed
  - jekyll-autoprefixer
  - jekyll-seo-tag
  - jekyll-menus

# Set Jekyll's env to enable/disable Uglifier
env: production

permalink: pretty

collections:
  artwork:
    output: true
    permalink: /artwork/:slug
  galleries:
    output: false
  museums:
    output: false  

sass:
  style: compressed

# stitch:
#   dependencies: 
#     - 'js/jquery.min.js'
#     - 'js/bootstrap.min.js'
#     - 'js/site.js'
#     - 'js/prism.min.js'
#     - 'js/clipboard.js'
#     - 'js/anchor.min.js'
#     - 'js/modernizr.custom.js'
#     - 'js/masonry.pkgd.min.js'
#     - 'js/imagesloaded.js'
#     - 'js/classie.js'
#     - 'js/AnimOnScroll.js'
#     - 'js/photoswipe.js'
#     - 'js/photoswipe-ui-default.js'
#   output: 'js/main.min.js'
#   fingerprint: false
#   cleanup: true
#   uglify: true
#   uglify_options: {}  